### ISSUE TITLE
Template for Connecting AWS Account results in an S3 Denied Error

### ISSUE THREAD

**Issue by zachelliottwx** [aws-geospatial/amazon-location-features-demo-web#176]
When trying to load https://amazon-location-demo-resources.s3.amazonaws.com/main-cf-template.yaml an S3 error occurs. Appears that URL is not valid.

**Comment by natechensan** [comment]
Check the CFN templates in the readme. It is also throwing an S3 error regarding permission.

https://amazon-location-demo-resources.s3.us-west-2.amazonaws.com/default-unauth-resources-template.yaml

**Comment by natechensan** [comment]
The main-cf-template issue happens at demo app/site when trying to connect to an account

**Comment by cgalvan** [comment]
I synced w/ @zachelliottwx  offline, the README setup steps were updated in the following commit to load the template directly, so this is no longer an issue.

https://github.com/aws-geospatial/amazon-location-features-demo-web/commit/caff701ba1155bf97f70a53466057998befe6711
