### ISSUE TITLE
Explicitly note Contribution, License, and Getting Help sections in README

### ISSUE THREAD

**Issue by thehoneymad** [aws-geospatial/amazon-location-features-demo-web#4]
Any repository publicly hosted in AWS Geospatial should note Contribution, License, and Getting Help section in README following the guidance of Amazon Open Source Policy.

This repository is missing link to Contribution and Getting Help section.

Please see a sample in https://github.com/aws-geospatial/amazon-location-utilities-datatypes-js

**Comment by thehoneymad** [comment]
Assigned @erickzzh to hand this to appropriate contributors.

**Comment by neelmurt** [comment]
Checking in on this. I noticed we don't have these sections added yet. Is there still a plan to add these?

**Comment by its-aazizi** [comment]
@neelmurt @mbalfour-amzn Have raised the following 2 PRs to address this issue.
- [Demo repo](https://github.com/aws-geospatial/amazon-location-features-demo-web/pull/201)
- [Marketing repo](https://github.com/aws-geospatial/amazon-location-web-marketing/pull/191)

**Comment by mbalfour-amzn** [comment]
PRs have been reviewed and merged.
