### ISSUE TITLE
Cypress E2E Tests Failing for fetching multiple input boxes with cy.click()

### ISSUE THREAD

**Issue by TheRBajaj** [aws-geospatial/amazon-location-features-demo-web#82]
### What happened?

We see a subset of e2e cypress tests failing against `mainline`. Tests that are failing are the following:
1. userIsAbleToSearch
2. userIsAbleToUseGeofence
3. userIsAbleToUseTheSidebar
4. userIsAbleToUseTracker
5. userIsAbleToConnectAndDisconnectAwsAccount.

During our investigation, we found out that in these tests`cy.click()` is trying to fetch the input box by trying to filter input boxes with `[placeholder="Search"]` filter. 😮 This returnes 2 input boxes. One is hidden for mobile view.

The tests fail with the following error message:
`cy.click() can only be called on a single element. Your subject contained 2 elements. Pass { multiple: true } if you want to serially click each element.`

We tried running the github workflow of E2E tests against mainline using `gh workflow run`. But the `workflow_dispatch` trigger is not supported for this workflow.

So, we created a dummy branch from main to run the E2E tests #84 in order to determine if the fault was coming from main. The results were consistent with the test from #83, which was our original PR and is blocked due to this.

<img width="754" alt="image" src="https://github.com/aws-geospatial/amazon-location-features-demo-web/assets/46388171/57d2fe8c-77a4-4ede-8a42-23c1321b838c">

### Action Points:
We suggest the following action points:
1. Adding a HTML id for the desktop Search input box and amend the tests.
2. Ensuring that the mobile input box is not present in the HTML dom in desktop view. Adding an integration test case for this should help us from regression.
3. Additionally these workflows *should* be able to be triggered with `workflow_dispatch` event. We suggest to add that if there are no big red flags. :) 

If the investigation and suggested action points look correct, we will go ahead and create Github issues for the suggested paths forward. Happy to hear thoughts and misses.

**Comment by its-aazizi** [comment]
@mbalfour-amzn @TheRBajaj I believe the recent Cypress E2E tests have resolved this issue, I think we can close this issue now.

**Comment by mbalfour-amzn** [comment]
@TheRBajaj If you see the issue again, please open a new ticket. Thanks!
